service: citadel-slack-api

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    DYNAMODB_TABLE: citadel_table
  # TODO Need to update this with correct DynamoTable info.
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
        Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  update:
    handler: status/update.update
    description: Handles a citadel status/update API call from Slack.
    # added 'update' to the path to differentiate between updates and gets because they are both POST requests.
    events:
      - http: POST status/update
        cors: true
    tags:
      Name: "Citadel"
      Owner: "ryan.bruun@cloudreach.com"
      Purpose: "Citadel/Skunkworks"

  get:
      handler: status/get.get
      description: Handles a citadel POST status/get API call from Slack.
      # this is a POST instead of a GET because Slack API only does POST.
      events:
        - http: POST status/{slackUserId}
          cors: true
      tags:
        Name: "Citadel"
        Owner: "ryan.bruun@cloudreach.com"
        Purpose: "Citadel/Skunkworks"

